name: Check Master
on:
  push:
    branches:
      master

jobs:
  master:
    name: master check
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run unit tests
        shell: bash
        run: ./gradlew test